name: Feature Branch
on:
  pull_request:
    branches: ["main"]
    types: [opened, synchronize, reopened, labeled]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  id-token: write
  contents: read
  checks: write

jobs:
  build:
    runs-on: ["ubuntu-latest"]
    steps:
      - name: Install Atmos
        uses: cloudposse/github-action-setup-atmos@v2
        with:
          install-wrapper: false
          atmos-version: ${{ vars.ATMOS_VERSION }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: ECR password
        shell: bash
        run: |
          atmos auth exec --identity plat-dev/terraform -- aws configure export-credentials --format env-no-export >> $GITHUB_ENV
        env:
          ATMOS_PROFILE: github

      - name: Mask ECR credentials
        shell: bash
        run: |
          echo "::mask::${{ env.AWS_SECRET_ACCESS_KEY }}"
          echo "::mask::${{ env.AWS_ACCESS_KEY_ID }}"
          echo "::mask::${{ env.AWS_SESSION_TOKEN }}"

      - name: Login to ECR
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.ECR_REGISTRY }}

      - name: Build
        id: build
        uses: cloudposse/github-action-docker-build-push@v2
        with:
          organization: cloudposse-examples
          repository: app-on-ecs-v2
          registry: ${{ vars.ECR_REGISTRY }}
          workdir: app

    outputs:
      image: ${{ steps.build.outputs.image }}
      tag: ${{ steps.build.outputs.tag }}

  deploy:
    needs: [ build ]
    runs-on: ["ubuntu-latest"]
    if: ${{ contains(github.event.pull_request.labels.*.name, 'deploy') }}
    environment:
      name: preview
      url: ${{ steps.deploy.outputs.output_url }}
    steps:
      - name: Install Atmos
        uses: cloudposse/github-action-setup-atmos@v2
        with:
          install-wrapper: false
          atmos-version: ${{ vars.ATMOS_VERSION }}

      - name: Checkout
        uses: actions/checkout@v4

      - uses: opentofu/setup-opentofu@v1
        with:
          tofu_wrapper: false
          tofu_version_file: .opentofu-version

      - name: Deploy ECS Service
        shell: bash
        id: deploy
        env:
          APP_IMAGE: "${{ needs.build.outputs.image }}:${{ needs.build.outputs.tag }}"
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ATMOS_PROFILE: github
        run: |
          atmos toolchain install
          atmos terraform deploy app -s preview
