name: Release
on:
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  id-token: write
  contents: read
  checks: write

env:
  ATMOS_PROFILE: github

jobs:
  promote:
    runs-on: ["ubuntu-latest"]
    container:
      image: ghcr.io/cloudposse/atmos:${{ vars.ATMOS_VERSION }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Install Docker CLI
        run: apt-get update && apt-get install -y docker.io

      - name: Checkout
        uses: actions/checkout@v6

      - name: AWS Auth
        run: |
          atmos auth env --identity plat-dev/terraform --format dotenv | tr -d "'" >> $GITHUB_ENV
          atmos auth login --identity plat-dev/terraform

      - uses: cloudposse/github-action-docker-promote@v1
        id: promote
        with:
          organization: cloudposse-examples
          repository: atmos-native-ci
          registry: ${{ vars.ECR_REGISTRY }}
          from: sha-${{ github.sha }}
          to: ${{ github.event.release.tag_name }}
          use_metadata: false
  
    outputs:
      image: ${{ steps.promote.outputs.image }}
      tag: ${{ steps.promote.outputs.tag }}
      
  deploy-staging:
    needs: [ promote ]
    runs-on: ["ubuntu-latest"]
    container:
      image: ghcr.io/cloudposse/atmos:${{ vars.ATMOS_VERSION }}
    name: deploy / staging
    environment:
      name: staging
      url: ${{ steps.deploy.outputs.url }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Deploy ECS Service
        id: deploy
        env:
          ATMOS_PROFILE: github
          APP_IMAGE: "${{ needs.promote.outputs.image }}:${{ needs.promote.outputs.tag }}"
        run: |
          atmos terraform deploy app -s staging

  deploy-production:
    needs: [ deploy-staging, promote ]
    runs-on: ["ubuntu-latest"]
    container:
      image: ghcr.io/cloudposse/atmos:${{ vars.ATMOS_VERSION }}
    name: deploy / production
    environment:
      name: prod
      url: ${{ steps.deploy.outputs.url }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Deploy ECS Service
        id: deploy
        env:
          ATMOS_PROFILE: github
          APP_IMAGE: "${{ needs.promote.outputs.image }}:${{ needs.promote.outputs.tag }}"
        run: |
          atmos terraform deploy app -s prod
          
